---
title: Roosje Pertz
timezone: Europe/Brussels
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
sass:
  sass_dir: assets/css
  style: compressed
plugins:
- jekyll-autoprefixer
- jekyll-seo-tag
- jekyll-sitemap
email: info@roosjepertz.be
description: 'Website van stand-up comedienne Roosje Pertz.

'
baseurl:
url: http://www.roosjepertz.be
twitter_username:
tagline: Website van stand-up comedienne Roosje Pertz.
author: Edouard De Prez
google_analytics:
twitter:
  username: roosjepertz
