

sass:
  sass_dir: assets/css

plugins:
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap

title: Roosje Pertz
email: info@roosjepertz.be
description: > # this means to ignore newlines until "baseurl:"
  Website van stand-up comedienne Roosje Pertz.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.roosjepertz.be" # the base hostname & protocol for your site

twitter_username:

tagline: "Website van stand-up comedienne Roosje Pertz."
author: Edouard De Prez
google_analytics:
twitter:
  username: roosjepertz
